name: Verify PR Labels

on:
  pull_request:
    branches: [ master ]
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  steps:
    uses: jesusvasquez333/verify-pr-label-action@v1.4.0
    with:
      github-token: '${{ secrets.GITHUB_TOKEN }}'
      valid-labels: 'pr: non-breaking, pr: breaking change, pr: new feature'
      disable-reviews: true
