# This is a basic workflow to help you get started with Actions

name: Falcor Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [Windows, self-hosted]
    timeout-minutes: 100
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        configuration: ['Release']
        platform: ['x64']
        include:
          - platform: x64
            testPlatform: x64
          - platform: x64
            testCategory: full
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: setup-falcor
      run: |
        git clone --recursive https://gitlab-master.nvidia.com/yhe/Falcor
        cd Falcor
        git checkout ci-fix
        .\setup-vs2022.bat
        MSBuild.exe Falcor.sln -v:m -m -property:Configuration=Release -property:Platform=x64 -maxcpucount:12
        cd ..\
        mkdir FalcorBin
        cd FalcorBin
        Copy-Item -Path '..\Falcor\build\windows-vs2022\bin\*' -Destination '.\build\windows-vs2022\bin\' -Recurse -Exclude ("*.pdb")
        Copy-Item -Path '..\Falcor\tests' -Destination '.\tests\' -Recurse
        Copy-Item -Path '..\Falcor\tools' -Destination '.\tools\' -Recurse
        Copy-Item -Path '..\Falcor\media' -Destination '.\media\' -Recurse
        Copy-Item -Path '..\Falcor\media_internal' -Destination '.\media_internal\' -Recurse
        Copy-Item -Path '..\Falcor\scripts' -Destination '.\scripts\' -Recurse
        cd ..\
    - name: build
      run: |
        .\premake.bat vs2019 --arch=${{matrix.platform}} --deps=true --no-progress=true --enable-cuda=true
        
        .\make-slang-tag-version.bat
        
        MSBuild.exe slang.sln -v:m -m -property:Configuration=${{matrix.configuration}} -property:Platform=${{matrix.platform}} -property:WindowsTargetPlatformVersion=10.0.19041.0 -maxcpucount:12
    - name: falcor-unit-test
      run: |
        $ErrorActionPreference = "SilentlyContinue"
        cd .\FalcorBin\tests
        python ./testing/run_unit_tests.py
        cd ../../
    - name: falcor-image-test
      run: |
        $ErrorActionPreference = "SilentlyContinue"
        cd .\FalcorBin\tests
        python ./testing/run_image_tests.py
        cd ../../
      
